FEATURES_CUSTOM_CALLBACK = {
  'global_namespace' : str,
  'global_ttl' : int,
  'policiesByServerPoolFeature' : bool,
  'messagesBySecFeature' : bool,
  'messagesBySecStoreDays' : int,
  'feederFeaturesEnabled' : bool,
  'featuresByServerPool' : bool,
  'learnFeature' : bool,
  'learnPredictSafeValue' : float,
  'learnOnlyOnce' : bool,
  'learnEscalationValue' : float,
  'learnTimeFrameValue' : list,
  'learnBlockMinutes' : float,
  'rateReputationFeature' : bool,
  'rateReputationBlockHitValue' : int,
  'rateReputationDecreaseValue' : float,
  'rateReputationIncreaseMinutes' : float,
  'ipReputationFeature' : bool,
  'ipReputationHitValue' : int,
  'ipReputationDecreaseValue' : float,
  'ipReputationIncreaseMinutes' : float,
  'subjectReputationFeature' : bool,
  'subjectReputationHitValue' : int,
  'subjectReputationDecreaseValue' : float,
  'subjectReputationIncreaseMinutes' : float,
  'global_conditions' : list,
  'global_custom_block' : int
}

METADATA_CUSTOM_CALLBACK = {
  'learnPredictSafeValue' : float,
  'learnEscalationValue' : float,
  'subject_repeated_count' : int,
  'ip_reputation_lastupdate' : float,
  'subject_lastupdate' : float,
  'sentmessages_lastupdate' : float,
  'last_update' : float,
  'last_subject' : str,
  'blue_creation_date' : float,
  'block_count' : int,
  'learningBlueMode' : bool,
  'learningRedMode' : bool,
  'manual_block' : bool,
  'predictBy' : str,
  'bypass' : bool
}

POLICY_CUSTOM_CALLBACK = {
  'enable' : bool,
  'stophere' : bool,
  'requestsmon' : bool,
  'countrcpt' : bool, 
  'ipprobation' : float,
  'subjectprobation' : float,
  'countsentprobation' : float,
  'blockprobation' : float,
  'priority' : int,
  'jailspec' : list,
  'onlyheaders' : bool,
  'actionheaders' : dict
}

DEFAULT_POLICY_PARAMS = {
  'Enable' : True,
  'Type' : 'regular',
  'Priority' : 5,
  'JailBy' : 'Sender+',
  'JailSpec' : '0:0',
  'JailAction' : 'monitor',
  'ReplyData' : 'Limit reached. Blocking for %s second(s)',
  'CountSentProbation' : 1,
  'CountRCPT' : False,
  'StopHere' : False,
  'RequestsMon' : False,
  'SubjectProbation' : 0.5,
  'IpProbation' : 0.5,
  'BlockProbation' : 0.5,
  'CountSentProbation' : 1,
  'ActionHeaders' : {},
  'OnlyHeaders' : False
}