#! /bin/bash

### BEGIN INIT INFO
# Provides:          themisd
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Postfix milter behavior rate limiter
# Description:       Themis is a policy daemon to predict and control the rate of sending mails in Postfix
### END INIT INFO

# Author: Sandro Mello <sandromll@gmail.com>
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=themismilter
DESC="operations management daemon"
DAEMON=themismilter
DAEMON_BIN=/usr/sbin/themismilter.py
DAEMON_PIDFILE=/var/run/$DAEMON.pid
SCRIPTNAME=/etc/init.d/$NAME

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Define LSB log_* functions.
. /lib/lsb/init-functions

rc_syntax()
{
    if test -z "$LINES" -o -z "$COLUMNS" ; then
    eval `exec 3<&1; stty size <&3 2>/dev/null | (read L C; \
    echo LINES=${L:-24} COLUMNS=${C:-80})`
    fi

    if test -t 1 -a "$TERM" != "raw" -a "$TERM" != "dumb" && stty size <&1 > /dev/null 2>&1 ; then
    esc=`echo -en "\033"`
    extd="${esc}[1m"
    warn="${esc}[1;31m"
    attn="${esc}[1;33m"
    norm=`echo -en "${esc}[m\017"`
    stat=`echo -en "\015${esc}[${COLUMNS}C${esc}[10D"`
    done="${esc}[1;32m"
    else
    esc=""
    extd=""
    warn=""
    attn=""
    norm=""
    stat=""
    done=""
    fi

    rc_done="${stat}${done}done${norm}"
    rc_started="${stat}${done}already started${norm}"
    rc_stopped="${stat}${done}already stopped${norm}"
    rc_not_installed="${stat}${extd}not installed${norm}"
    rc_failed="${stat}${warn}failed${norm}"
}

rc_syntax

service_start() {
    log_daemon_msg "Starting $DESC" "$DAEMON. "
    touch $DAEMON_PIDFILE
    chown themisd:themisd $DAEMON_PIDFILE
    if [ -f $DAEMON_BIN ]; then
        if start-stop-daemon --background --start --quiet --umask 007 --chuid themisd:themisd --exec $DAEMON_BIN --pidfile $DAEMON_PIDFILE --make-pidfile
    then
        echo $rc_done
    else
        echo $rc_failed
    fi
    else
        echo $rc_not_installed
    exit 3
    fi
}

service_stop() {
    log_daemon_msg "Stopping $DESC" "$DAEMON. "
    if [ -f $DAEMON_BIN ]; then
        start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $DAEMON_PIDFILE --signal INT
        case "$?" in
            0) echo $rc_done && echo > $DAEMON_PIDFILE ;;
            *) echo $rc_failed ;;
        esac
    else
        echo $rc_not_installed
        exit 3
    fi
}

case "$1" in
  start)
    service_start
    ;;
  stop)
    service_stop
    ;;
  restart)
    service_stop
    service_start
    ;;
  force-reload)
    service_stop
    service_start
    ;;
  flush)
    service_flush
    ;;
  status)
    status_of_proc -p $DAEMON_PIDFILE $DAEMON_BIN $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
    exit 2
    ;;
esac

: