#!/usr/bin/env python
import getopt, sys, os
import json, yaml
from traceback import format_exc
from os.path import expanduser
from themis import 
from themis.group import GroupError

# TODO: List available options for policy
# TODO: Create automatic pool on policy creation, should delete when a pool policy is deleted
# TODO: Should not delete a pool if exists a policy associate with
# TODO: get operations should accept only one key too, E.G.: tmsprov -g --metadata metadata:lab01.domain.tld manual_block
# TODO: List of metadata keys/values and features keys/values
# TODO: lock destination any with bypass

if __name__ == '__main__':
